package element

// nobel --> reactive-no

var elementList = map[string]Element{
	"h":  {"H", 1, "Hydrogen", true, "", "Simple at heart and light in your mood. You bond to things easily and love being around people."},
	"he": {"He", 2, "Helium", true, "adaptable-hi,available-lo,bold-lo,creative-lo,dependable-lo,fair-hi,rich-hi,honest-hi,explosive-lo,cooperative-hi,noble-hi,solid-lo,toxic-lo,fickle-lo,brilliant-lo,attractive-lo,colorful-lo,simple-hi,earthy-lo", "Light and nobel at heart you rarely react. You soar above everything."},
	"li": {"Li", 3, "Lithium", true, "", "You barely react to others. You are light at heart and float above all pettiness."},
	"be": {"Be", 4, "Beryllium", true, "", "You are strong and impart strength to others. A symbol of strength and stability and rarely get angry"},
	"b":  {"B", 5, "Boron", true, "", "You make a great freind and bond well with others who are like you. You rarely have a meltdown."},
	"c":  {"C", 6, "Carbon", true, "adaptable-lo,available-hi,bold-lo,creative-hi,dependable-hi,cooperative-lo,lovable-lo,noble-lo,solid-hi,toxic-lo,fickle-lo,brilliant-lo,attractive-hi,colorful-lo,modest-hi,earthy-lo", "Extremely creative, you are always readily available, and always the life of the party. The engine to life’s machine."},
	"n":  {"N", 7, "Nitrogen", true, "adaptable-hi,available-hi,bold-hi,dependable-lo,cooperative-hi,lovable-hi,noble-lo,solid-lo,toxic-lo,attractive-lo,colorful-lo,modest-hi,earthy-lo", "You are extremely adaptable and ever available for those who need you. Bold, cooperative, and friendly, you make friends easily and your modest nature makes you all the more appealing."},
	"o":  {"O", 8, "Oxygen", true, "adaptable-hi,available-hi,bold-hi,dependable-hi,rich-lo,honest-lo,explosive-hi,cooperative-hi,lovable-hi,noble-lo,solid-lo,toxic-lo,fickle-lo,brilliant-lo,attractive-lo,colorful-lo,modest-hi,earthy-lo", "You react violently with others. Even though people take little notice of you, you are the life of any party you attend."},
	"f":  {"F", 9, "Fluorine", true, "adaptable-hi,available-hi,bold-hi,creative-hi,dependable-lo,fair-lo,generous-lo,rich-hi,explosive-hi,cooperative-hi,lovable-hi,noble-lo,solid-lo,toxic-hi,fickle-lo,brilliant-lo,attractive-lo,simple-lo,earthy-lo", "You are light and fluid and like to go with the flow, living everyday as it comes."},
	"ne": {"Ne", 10, "Neon", true, "adaptable-hi,available-lo,bold-lo,creative-lo,dependable-lo,fair-hi,generous-hi,rich-hi,honest-hi,explosive-lo,cooperative-lo,lovable-lo,noble-hi,solid-lo,toxic-lo,fickle-lo,brilliant-lo,attractive-lo,colorful-lo,modest-lo,earthy-lo", "You are known as a fair and generous person and are known for your morals. No matter what anyone says, you will always have your noble grace and be rich in your own qualities."},
	"na": {"Na", 11, "Sodium", true, "", ""},
	"mg": {"Mg", 12, "Magnesium", true, "", ""},
	"al": {"Al", 13, "Aluminum", true, "", ""},
	"si": {"Si", 14, "Silicon", true, "adaptable-lo,bold-lo,creative-hi,dependable-hi,cooperative-hi,lovable-lo,noble-lo,solid-hi,toxic-lo,fickle-hi,brilliant-lo,attractive-hi,colorful-hi,modest-hi", "Your creativity outshines most and your cooperative and modest personality draws many people in. You are extremely well liked. With your colorful and attractive nature, who wouldn’t?"},
	"p":  {"P", 15, "Phosphorus", true, "adaptable-lo,bold-hi,dependable-hi,lovable-hi,noble-lo,solid-hi,toxic-hi,brilliant-hi,attractive-lo,colorful-hi,modest-hi,earthy-hi", "You are bold and outgoing, lovable and friendly all around. You are intelligent, and your personality is very colorful but your modesty make you all the more appealing."},
	"s":  {"S", 16, "Sulfur", true, "adaptable-lo,available-hi,bold-hi,dependable-hi,rich-lo,cooperative-hi,lovable-hi,noble-lo,solid-hi,toxic-hi,fickle-hi,brilliant-hi,attractive-lo,colorful-hi,modest-hi,earthy-lo", "You are solid in your views and morals and are unwavering when it comes to others. You bond easily with other people and are a very dependable person."},
	"cl": {"Cl", 17, "Chlorine", true, "adaptable-hi,available-hi,bold-hi,creative-hi,dependable-lo,fair-lo,generous-lo,rich-lo,explosive-hi,cooperative-hi,lovable-hi,noble-lo,solid-lo,toxic-hi,fickle-lo,brilliant-lo,attractive-lo,colorful-lo,simple-lo,earthy-lo", "You are prepared for whatever comes your way, and can react fast to any situation. You are most likely very fast, or a very quick thinker."},
	"ar": {"Ar", 18, "Argon", true, "adaptable-hi,available-hi,bold-lo,dependable-lo,generous-hi,rich-lo,honest-hi,cooperative-lo,lovable-lo,noble-hi,solid-lo,toxic-lo,fickle-lo,brilliant-lo,attractive-lo,colorful-lo,modest-lo,complex-hi,earthy-lo", "You are a light hearted and agreeable person and you are very graceful and noble in your bearing. You are a pretty hard person to understand sometimes, but you are really a very kind hearted person."},
	"k":  {"K", 19, "Potassium", true, "", ""},
	"ca": {"Ca", 20, "Calcium", true, "", ""},
	"sc": {"Sc", 21, "Scandium", true, "", ""},
	"ti": {"Ti", 22, "Titanium", true, "", ""},
	"v":  {"V", 23, "Vanadium", true, "", ""},
	"cr": {"Cr", 24, "Chromium", true, "", ""},
	"mn": {"Mn", 25, "Manganese", true, "", ""},
	"fe": {"Fe", 26, "Iron", true, "", ""},
	"co": {"Co", 27, "Cobalt", true, "", ""},
	"ni": {"Ni", 28, "Nickel", true, "", ""},
	"cu": {"Cu", 29, "Copper", true, "", ""},
	"zn": {"Zn", 30, "Zinc", true, "", ""},
	"ga": {"Ga", 31, "Gallium", true, "", ""},
	"ge": {"Ge", 32, "Germanium", true, "adaptable-lo,bold-lo,creative-hi,dependable-hi,lovable-lo,noble-lo,solid-hi,toxic-lo,fickle-hi,brilliant-hi,attractive-hi,colorful-hi,earthy-hi", "Extremely dependable, you are a well-grounded person and firm in your beliefs. Creative and smart, people are drawn to you, despite your sometimes timid personality."},
	"as": {"As", 33, "Arsenic", true, "adaptable-lo,bold-hi,dependable-hi,rich-hi,noble-lo,solid-hi,toxic-hi,fickle-hi,brilliant-hi,attractive-hi,colorful-lo,modest-lo", "You are a bold and a very dependable person with amazing intelligence and brilliance. You’re a very attractive person and are loved by everyone."},
	"se": {"Se", 34, "Selenium", true, "adaptable-lo,dependable-hi,cooperative-hi,noble-lo,solid-hi,colorful-hi", "You are a very kind and cooperative person. You are dependable and are always a solid person to lean on."},
	"br": {"Br", 35, "Bromine", true, "adaptable-hi,available-lo,bold-hi,creative-hi,fair-lo,generous-lo,rich-lo,explosive-hi,cooperative-hi,lovable-hi,noble-lo,toxic-hi,fickle-lo,brilliant-lo,attractive-lo,modest-lo,simple-lo,earthy-lo", "You are a very agreeable person and you get along with people easily. But when it comes to grudges or enemies, you are more than a little salty."},
	"kr": {"Kr", 36, "Krypton", true, "adaptable-hi,available-lo,bold-lo,creative-lo,dependable-lo,rich-hi,honest-hi,explosive-lo,cooperative-lo,lovable-lo,noble-hi,solid-lo,toxic-lo,brilliant-lo,attractive-lo,colorful-lo,earthy-lo", "You are a very honest and adaptable person. Though you are kind of timid, your lofty and noble attitude is sure to put everyone back in their place."},
	"rb": {"Rb", 37, "Rubidium", true, "", ""},
	"sr": {"Sr", 38, "Strontium", true, "", ""},
	"y":  {"Y", 39, "Yttrium", true, "", ""},
	"zr": {"Zr", 40, "Zirconium", true, "", ""},
	"nb": {"Nb", 41, "Niobium", true, "", ""},
	"mo": {"Mo", 42, "Molybdenum", true, "", ""},
	"tc": {"Tc", 43, "Technetium", true, "", ""},
	"ru": {"Ru", 44, "Ruthenium", true, "", ""},
	"rh": {"Rh", 45, "Rhodium", true, "", ""},
	"pd": {"Pd", 46, "Palladium", true, "", ""},
	"ag": {"Ag", 47, "Silver", true, "", ""},
	"cd": {"Cd", 48, "Cadmium", true, "", ""},
	"in": {"In", 49, "Indium", true, "", ""},
	"sn": {"Sn", 50, "Tin", true, "adaptable-lo,available-hi,bold-hi,creative-hi,dependable-hi,cooperative-hi,lovable-hi,noble-lo,solid-hi,toxic-lo,fickle-lo,brilliant-hi,attractive-hi,colorful-hi,modest-hi,earthy-hi", "Creative, bold, and dependable, you are very attractive for anyone looking for a friend. Lovable, friendly, and smarts, accompanied by modesty, people genuinely admire you and your amazing qualtiies."},
	"sb": {"Sb", 51, "Antimony", true, "adaptable-lo,dependable-hi,noble-lo,solid-hi,toxic-lo,fickle-lo,brilliant-hi,attractive-hi,colorful-lo,modest-lo", "You are firm in your values and very dependable. Increasingly smart, your personality attracts many admirers to your court."},
	"te": {"Te", 52, "Tellurium", true, "adaptable-lo,available-lo,bold-hi,dependable-hi,rich-hi,cooperative-hi,lovable-hi,noble-lo,solid-hi,toxic-hi,fickle-lo,brilliant-lo,attractive-hi,colorful-hi,modest-lo,earthy-hi", "You are a very attractive person with your colorful and bold personality. You are dependable, lovable, cooperative, with a rare allure that makes you stand out amongst others."},
	"i":  {"I", 53, "Iodine", true, "adaptable-lo,available-lo,bold-hi,dependable-hi,generous-hi,rich-lo,cooperative-hi,noble-lo,solid-hi,fickle-lo,attractive-hi,colorful-hi,modest-lo,simple-lo,earthy-lo", "You are a lovable person with solid opinions. Adored by all, you can make anyone�s heard pump faster."},
	"xe": {"Xe", 54, "Xenon", true, "adaptable-hi,available-lo,bold-lo,creative-lo,dependable-lo,fair-lo,generous-hi,rich-hi,honest-hi,explosive-hi,cooperative-lo,lovable-lo,noble-hi,solid-lo,toxic-lo,brilliant-hi,attractive-lo,colorful-lo,simple-lo,earthy-lo", "You are brilliant person and are probably known for your noble stature and your generosity. You are rich in your qualities and are one of the most honest people on the planet."},
	"cs": {"Cs", 55, "Cesium", true, "", ""},
	"ba": {"Ba", 56, "Barium", true, "", ""},
	"la": {"La", 57, "Lanthanum", true, "", ""},
	"ce": {"Ce", 58, "Cerium", true, "", ""},
	"pr": {"Pr", 59, "Praseodymium", true, "", ""},
	"nd": {"Nd", 60, "Neodymium", true, "", ""},
	"pm": {"Pm", 61, "Promethium", true, "", ""},
	"sm": {"Sm", 62, "Samarium", true, "", ""},
	"eu": {"Eu", 63, "Europium", true, "", ""},
	"gd": {"Gd", 64, "Gadolinium", true, "", ""},
	"tb": {"Tb", 65, "Terbium", true, "", ""},
	"dy": {"Dy", 66, "Dysprosium", true, "", ""},
	"ho": {"Ho", 67, "Holmium", true, "", ""},
	"er": {"Er", 68, "Erbium", true, "", ""},
	"tm": {"Tm", 69, "Thulium", true, "", ""},
	"yb": {"Yb", 70, "Ytterbium", true, "", ""},
	"lu": {"Lu", 71, "Lutetium", true, "", ""},
	"hf": {"Hf", 72, "Hafnium", true, "", ""},
	"ta": {"Ta", 73, "Tantalum", true, "", ""},
	"w":  {"W", 74, "Tungsten", true, "", ""},
	"re": {"Re", 75, "Rhenium", true, "", ""},
	"os": {"Os", 76, "Osmium", true, "", ""},
	"ir": {"Ir", 77, "Iridium", true, "", ""},
	"pt": {"Pt", 78, "Platinum", true, "", ""},
	"au": {"Au", 79, "Gold", true, "", ""},
	"hg": {"Hg", 80, "Mercury", true, "", ""},
	"tl": {"Tl", 81, "Thallium", true, "", ""},
	"pb": {"Pb", 82, "Lead", true, "adaptable-lo,available-hi,bold-lo,creative-hi,dependable-hi,cooperative-hi,lovable-lo,noble-lo,solid-hi,toxic-hi,fickle-lo,brilliant-lo,attractive-hi,colorful-lo,rich-lo,earthy-hi", "You are dependable and down to earth, with a penchant for abstract ideas, and usually come up with many creative angles to the same thing. This shouldn’t be hard to do of course, with your cooperative attitude and amazing artistic abilities."},
	"bi": {"Bi", 83, "Bismuth", true, "adaptable-lo,available-hi,dependable-hi,noble-lo,solid-hi,toxic-lo,fickle-lo,brilliant-hi,attractive-hi,colorful-lo,modest-lo,earthy-hi", "A dependable and grounded person, you are always available for your friends and ready to help them with your boundless wisdom."},
	"po": {"Po", 84, "Polonium", true, "adaptable-lo,available-lo,dependable-hi,cooperative-lo,lovable-lo,noble-lo,solid-hi,toxic-hi,fickle-hi,brilliant-hi,modest-lo,earthy-hi", "You are an extremely intelligent person, with your thoughts constantly trying to get out. Passionate and relentless when it comes down to it, you are insanely smart and very talented."},
	"at": {"At", 85, "Astatine", true, "adaptable-lo,available-lo,bold-hi,creative-lo,dependable-hi,fair-hi,generous-hi,rich-lo,cooperative-hi,noble-lo,solid-hi,fickle-hi,brilliant-hi,attractive-hi,colorful-hi,modest-lo,simple-lo,earthy-hi", "You are brilliant person, with lots of thoughts trying to get out. Though not very hardy, you blow people away with your radioactive intelligence."},
	"rn": {"Rn", 86, "Radon", true, "adaptable-hi,bold-lo,creative-lo,dependable-lo,fair-hi,honest-hi,explosive-lo,cooperative-lo,lovable-lo,noble-hi,solid-lo,toxic-lo,fickle-hi,brilliant-hi,attractive-lo,colorful-lo,modest-lo,simple-lo,earthy-lo", "You are an incredibly smart person and are probably known as ‘the brilliant one’. You are honest and noble and are very adaptable. You are a person of ethics and morals and are known as a great person to be around"},
	"fr": {"Fr", 87, "Francium", true, "", ""},
	"ra": {"Ra", 88, "Radium", true, "", ""},
	"ac": {"Ac", 89, "Actinium", true, "", ""},
	"th": {"Th", 90, "Thorium", true, "", ""},
	"pa": {"Pa", 91, "Protactinium", true, "", ""},
	"u":  {"U", 92, "Uranium", true, "", ""},
	"np": {"Np", 93, "Neptunium", true, "", ""},
	"pu": {"Pu", 94, "Plutonium", true, "", ""},
	"am": {"Am", 95, "Americium", true, "", ""},
	"cm": {"Cm", 96, "Curium", true, "", ""},
	"bk": {"Bk", 97, "Berkelium", true, "", ""},
	"cf": {"Cf", 98, "Californium", true, "", ""},
	"es": {"Es", 99, "Einsteinium", true, "", ""},
	"fm": {"Fm", 100, "Fermium", true, "", ""},
	"md": {"Md", 101, "Mendelevium", true, "", ""},
	"no": {"No", 102, "Nobelium", true, "", ""},
	"lr": {"Lr", 103, "Lawrencium", true, "", ""},
	"rf": {"Rf", 104, "Rutherfordium", true, "", ""},
	"db": {"Db", 105, "Dubnium", true, "", ""},
	"sg": {"Sg", 106, "Seaborgium", true, "", ""},
	"bh": {"Bh", 107, "Bohrium", true, "", ""},
	"hs": {"Hs", 108, "Hassium", true, "", ""},
	"mt": {"Mt", 109, "Meitnerium", true, "", ""},
	"ds": {"Ds", 110, "Darmstadtium", true, "", ""},
	"rg": {"Rg", 111, "Roentgenium", true, "", ""},
	"cn": {"Cn", 112, "Copernicium", true, "", ""},
	"nh": {"Nh", 113, "Nihonium", true, "", ""},
	"fl": {"Fl", 114, "Flerovium", true, "adaptable-hi,available-lo,bold-lo,creative-hi,dependable-lo,cooperative-lo,lovable-lo,noble-lo,solid-lo,toxic-hi,fickle-hi,brilliant-hi", "Incredibly adaptable, you may be one of the most flexible people you know. This is amazingly useful, especially when it comes to your creative flow and annoying people (we all know some). You are known for complex and abstract ideas, which seems obvious with your stellar smarts and creative mind. People know not to mess with you."},
	"mc": {"Mc", 115, "Moscovium", true, "adaptable-lo,available-lo,bold-hi,dependable-hi,rich-lo,cooperative-lo,lovable-hi,noble-lo,solid-hi,toxic-hi,fickle-hi,brilliant-hi", "You are one of the most brilliantly smart people to ever grace this world. You are bold and audacious and always dependable. Lovable and friendly, people love to be around you."},
	"lv": {"Lv", 116, "Livermorium", true, "adaptable-lo,available-lo,dependable-hi,rich-lo,cooperative-lo,lovable-lo,noble-lo,solid-hi,fickle-hi,brilliant-hi", "A very dependable person, you are always there for people as a grounding support. Extremely smart and passionate about whatever you do, your talent is almost explosive."},
	"ts": {"Ts", 117, "Tennessine", true, "", ""},
	"og": {"Og", 118, "Oganesson", true, "adaptable-hi,available-lo,bold-lo,dependable-lo,generous-hi,honest-hi,cooperative-lo,lovable-lo,noble-hi,solid-lo,fickle-hi,brilliant-hi,attractive-lo,colorful-lo,modest-lo,complex-lo,earthy-lo", "You are brilliant person and you love to work like you’re running out of time. You are very noble and fair and a generally great person to be around."},
	"a": {"A", 119, "Arbitrarium", false, "", ""},
	"d": {"D", 120, "Doubtium", false, "", ""},
	"e": {"E", 121, "Exoticium", false, "", ""},
	"g": {"G", 122, "Grandiosium", false, "", ""},
	"j": {"J", 123, "Jocerium", false, "", ""},
	"l": {"L", 124, "Loverium", false, "", ""},
	"m": {"M", 125, "Magicinium", false, "", ""},
	"q": {"Q", 126, "Queenium", false, "", ""},
	"r": {"R", 127, "Royalium", false, "", ""},
	"t": {"T", 128, "Techium", false, "", ""},
	"x": {"X", 129, "Misterium", false, "", ""},
	"z": {"Z", 130, "Zanthium", false, "", ""},
}
